### ISSUE TITLE
Temporal Cloud dashboard doesn't work with Grafana Cloud

### ISSUE THREAD

**Issue by ledniy** [temporalio/dashboards#41]
Whenever I open the dashboard, I get the following error: `client_error: error parsing param: query, error: batch queries are currently not supported` on all panels.

Grafana Cloud, version `v9.3.2-45365 (ef5286dd77)`

<img width="1659" alt="image" src="https://user-images.githubusercontent.com/1562848/208480251-a6c0a666-b6ce-4c98-a7c5-0c16644c5d8e.png">

**Comment by andrew-kolesnikov** [comment]
Same here - it works for `5 and 15 min window`, but fails for `1 hour `and beyond

**Comment by andrew-kolesnikov** [comment]
Which means it's unlikely to be a problem with the dashboard. Also the underlying `prom api query` returns results just fine which once again points to this being a Grafana Cloud issue.

**Comment by TimSimmons** [comment]
Hello! This is an issue with Grafana Cloud that we've run into.
It was introduced with https://github.com/grafana/grafana/pull/58365. If you open a ticket with them and ask them to toggle the `prometheusBufferedClient` feature toggle, it should work again.
It should be solved in 9.3.3 by this PR https://github.com/grafana/grafana/pull/60439, which "should be released in the next few days" as of Jan 3rd. So you may also be able to ask the to upgrade you to that.

**Comment by antmendoza** [comment]
Closing this issue, as per @TimSimmons comment
