### ISSUE TITLE
[Bug] Current sdk-general dashboard does not work for metrics emitted from Java SDK

### ISSUE THREAD

**Issue by antmendoza** [temporalio/dashboards#45]
### Describe the bug

I am setting up a dashboard for SDK metrics with Java and noticed that importing the sdk-general.json into grafana does not show any metric. 

- counter metrics does not have the suffix `_total`
- Java  SDK emits histogram metrics with the following format`${metrics}_seconds_bucket`, while in the dashboard use `${metrics}_bucket`
- the metric activity_endtoend_latency does not exist and there is a panel querying it

Should we fix the dashboard or create a new one for the Java SDK and see later if the same is working for other SDKs. I have not yet tested other SDKs but my plan is to do it if it helps. 

### Environment/Versions

- OS and processor: [e.g. M1 Mac, x86 Windows, Linux]
- Temporal Version: [e.g. 1.14.0?] and/or SDK version
- Are you using Docker or Kubernetes or building Temporal from source?

**Comment by antmendoza** [comment]
@tsurdilo @TimSimmons wdyt?

I can take this one if we agree on a solution

**Comment by TimSimmons** [comment]
a quick reading says to me that the java sdk is actually following https://prometheus.io/docs/practices/naming/ properly, so I'd create a separate dash for that with the hopes that eventually all would converge on that.
